name: Playwright Tests

on:
  repository_dispatch:
    types: [trigger-addmembers-workflow]
  push:
    branches: 
      - main
      - master
  pull_request:
    branches:
      - main
      - master
env:
  NAME: AshwinTest         
  PHONENUMBER: '7092310772' 
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Print input github
      run: |
        echo "Phone Number: ${{ github.event.client_payload.PHONENUMBER }}"
        echo "Contact Name: ${{ github.event.client_payload.NAME }}"

    - name: Run Playwright tests github
      run: |
        echo "Phone Number: ${{ github.event.client_payload.PHONENUMBER }}"
        echo "Contact Name: ${{ github.event.client_payload.NAME }}"
        npx playwright test

    - name: Print input
      run: |
        echo "Phone Number: $PHONENUMBER"
        echo "Contact Name: $NAME"

    - name: Run Playwright tests
      run: |
        echo "Phone Number: $PHONENUMBER"
        echo "Contact Name: $NAME"
        npx playwright test

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30




# name: Playwright Tests
# on:
#   push:
#     branches: 
#       - main
#       - master
#   pull_request:
#     branches:
#       - main
#       - master
#   workflow_dispatch:
#     inputs:
#       phoneNumber:
#         description: 'Phone number to send message to'
#         required: true
#         default: '7092310772'
#       contactName:
#         description: 'Contact name'
#         required: true
#         default: 'AshwinTest'
# jobs:
#   test:
#     timeout-minutes: 60
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v4
#     - uses: actions/setup-node@v4
#       with:
#         node-version: lts/*
#     - name: Install dependencies
#       run: npm ci
#     - name: Install Playwright Browsers
#       run: npx playwright install --with-deps
#     - name: Run Playwright tests
#       run: npx playwright test
#       env:
#         PHONE_NUMBER: ${{ env.NAME }}
#         CONTACT_NAME: ${{ github.event.inputs.contactName }}
#         DYNAMIC_VALUE: ${{ github.event.inputs.dynamicValue }}
#     - uses: actions/upload-artifact@v4
#       if: ${{ !cancelled() }}
#       with:
#         name: playwright-report
#         path: playwright-report/
#         retention-days: 30
