name: Playwright Tests

on:
  workflow_dispatch:
    inputs:
      GROUPNAME:
        description: 'Name of the group'
        required: true
        default: 'test1'
      
      PHONENUMBER:
        description: 'Number of the person'
        required: true
        default: '1234'
  repository_dispatch:
    types: [trigger-addmembers-workflow]
  push:
    branches: 
      - main
      - master
  pull_request:
    branches:
      - main
      - master
env:
  GROUPNAME: ${{ github.event.inputs.GROUPNAME }}         
  PHONENUMBER: ${{ github.event.inputs.PHONENUMBER }}
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Parameters through the github
      run: |
        echo "Phone Number : ${{ github.event.inputs.GROUPNAME }}"
        echo "Group Name : ${{ github.event.inputs.PHONENUMBER }}"
      env:
        GROUPNAME: ${{ github.event.inputs.GROUPNAME }}        
        PHONENUMBER: ${{ github.event.inputs.PHONENUMBER }} 
    - name: Install dependencies
      run: npm ci
    - name: Install only Chromium
      run: npx playwright install chromium
    - name: Print input
      run: |
        echo "Phone Number: $PHONENUMBER"
    - name: Run Playwright tests 
      run: |
        echo "Phone Number: $PHONENUMBER"
        npx playwright test .\AddMembers
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30



  #  - name: Install Playwright Browsers
  #     run: npx playwright install --with-deps
   # - name: Print input from repository_dispatch (client_payload)
    #   run: |
    #     echo "Phone Number (from repository_dispatch): ${{ github.event.client_payload }}"
    #     echo "Contact Name (from repository_dispatch): ${{ github.event.client_payloadih }}"
    #   env:
    #     NAME: ${{ github.event.client_payload.PHONENUMBER }}         
    #     PHONENUMBER: ${{ github.event.client_payload.NAME }} 
    # - name: Run Playwright tests with repository_dispatch inputs
    #   run: |
    #     echo "Phone Number (from repository_dispatch): ${{ github.event.inputs.PHONENUMBER }}"
    #     echo "Contact Name (from repository_dispatch): ${{ github.event.inputs.NAME }}"
    #     npx playwright test