name: Playwright Tests

on:
  push:
    branches: 
      - main
      - master
  pull_request:
    branches:
      - main
      - master
env:
  NAME: Ashwin         
  PHONENUMBER: 7092310772 

  # workflow_dispatch:
  #   inputs:
  #     phoneNumber:
  #       description: 'Phone number to send message to'
  #       required: true
  #       default: '7092310772'
  #     contactName:
  #       description: 'Contact name'
  #       required: true
  #       default: 'AshwinTest'
  #     dynamicValue:
  #       description: 'Dynamic value for testing'
  #       required: true
  #       default: 'testDynamicValue'

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Print input
      run: |
        echo "Phone Number: $PHONENUMBER"
        echo "Contact Name: $NAME"

    - name: Run Playwright tests
      run: |
        echo "Running Playwright tests with Phone Number: $PHONENUMBER"
        echo "Running Playwright tests with Contact Name: $NAME"
        npx playwright test
      env:
        PHONENUMBER: $PHONENUMBER
        CONTACT_NAME: $NAME

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30




# name: Playwright Tests
# on:
#   push:
#     branches: 
#       - main
#       - master
#   pull_request:
#     branches:
#       - main
#       - master
#   workflow_dispatch:
#     inputs:
#       phoneNumber:
#         description: 'Phone number to send message to'
#         required: true
#         default: '7092310772'
#       contactName:
#         description: 'Contact name'
#         required: true
#         default: 'AshwinTest'
# jobs:
#   test:
#     timeout-minutes: 60
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v4
#     - uses: actions/setup-node@v4
#       with:
#         node-version: lts/*
#     - name: Install dependencies
#       run: npm ci
#     - name: Install Playwright Browsers
#       run: npx playwright install --with-deps
#     - name: Run Playwright tests
#       run: npx playwright test
#       env:
#         PHONE_NUMBER: ${{ env.NAME }}
#         CONTACT_NAME: ${{ github.event.inputs.contactName }}
#         DYNAMIC_VALUE: ${{ github.event.inputs.dynamicValue }}
#     - uses: actions/upload-artifact@v4
#       if: ${{ !cancelled() }}
#       with:
#         name: playwright-report
#         path: playwright-report/
#         retention-days: 30
